# Project: TPLaboratorio v1.1
# Makefile created by Dev-C++ 4.9.9.2

CPP  = g++.exe
CC   = gcc.exe
WINDRES = windres.exe
RES  = 
OBJ  = TPLaboratorioV1.1.o miLibreriaV1.1.o $(RES)
LINKOBJ  = TPLaboratorioV1.1.o miLibreriaV1.1.o $(RES)
LIBS =  -L"C:/Dev-Cpp/lib"  -fmessage-length=0 
INCS =  -I"C:/Dev-Cpp/include" 
CXXINCS =  -I"C:/Dev-Cpp/lib/gcc/mingw32/3.4.2/include"  -I"C:/Dev-Cpp/include/c++/3.4.2/backward"  -I"C:/Dev-Cpp/include/c++/3.4.2/mingw32"  -I"C:/Dev-Cpp/include/c++/3.4.2"  -I"C:/Dev-Cpp/include" 
BIN  = "TPLaboratorio v1.1"
CXXFLAGS = $(CXXINCS)   -fmessage-length=0
CFLAGS = $(INCS)   -fmessage-length=0
RM = rm -f

.PHONY: all all-before all-after clean clean-custom

all: all-before "TPLaboratorio v1.1" all-after


clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CC) $(LINKOBJ) -o "TPLaboratorio v1.1" $(LIBS)

TPLaboratorioV1.1.o: TPLaboratorioV1.1.c
	$(CC) -c TPLaboratorioV1.1.c -o TPLaboratorioV1.1.o $(CFLAGS)

miLibreriaV1.1.o: miLibreriaV1.1.c
	$(CC) -c miLibreriaV1.1.c -o miLibreriaV1.1.o $(CFLAGS)
